#!/usr/bin/env python
""" Melt a VCF file into a tab delimited set of calls, one per line

VCF files have all the calls from different samples on one line.  This 
script reads vcf on stdin and writes all calls to stdout in tab delimited 
format with one call in one sample per line.  This makes it easy to find 
a given sample's genotype with, say, grep.
"""

import sys
import csv
import vcf

out = csv.writer(sys.stdout, delimiter='\t')
reader = vcf.VCFReader(sys.stdin)

formats = reader.formats.keys()
infos = reader.infos.keys()

header = ["SAMPLE"] + formats + ['info.'+ x for x in infos]


out.writerow(header)    

def flatten(x):
    if type(x) == type([]): 
        x = ','.join(map(str, x))
    return x

for record in reader: 
    info_row = [flatten(record.INFO.get(x, None)) for x in infos]
    for sample in record.samples: 
        row = [sample['name']]
        row += [flatten(sample.get(x, None)) for x in formats]
                
        row += info_row
        out.writerow(row)
